### ISSUE TITLE
Initial Test Issue to verify function

### ISSUE THREAD

**Issue by IanSuper7** [ukmars/ukmarsbot#1]
An examination of issues to see whether they are suitable for managing consultation feedback.

**Comment by IanSuper7** [comment]
What do you think Peter

**Comment by micromouseonline** [comment]
This is the way most github projects manage things. It is like a forum in that the history is all there and there are not ever-growing email lists with members forgetting to 'reply all'.

Email discussions are also useful though because everything on here is public.

**Comment by IanSuper7** [comment]
Looked into this to see if it was the best way to invite input in the collaboration periods. I think it is because once an issue has been raised and discussed it will be visible for all and could reduce a lot of overlapping and potentially conflicting emails. Agree there will be other discussions best conducted by email. My intention is to write this into the contributors guide as the vehicle for suggesting improvements in the collaboration windows.
