### ISSUE TITLE
Align Part Name conventions between UKMARSBot and Line Sensor

### ISSUE THREAD

**Issue by gbulmer** [ukmars/ukmarsbot#18]
**Phase:** Before PCBs for school trials are manufactured
**Artefacts impacted:** either UKMARSBot ECAD, or Line Sensor ECAD, or both

UKMARSBot uses 'LED' as the Part Name prefix for LEDs, and 'D' as the part name prefix for other types of diode.

Line Sensor uses 'LED' and 'D' as the Part Name prefix for LEDs, and has no other types of diode.

**Issue:** Part Naming should be consistent because the same people may be building both. 
Also it reinforces the notion that sound engineering principles are being used to design UKMARS Bot and Sensors.

_Comment_
I prefer 'LED' for all form of LEDs, visible or infrared, and 'D' for other types of diode (eg. junction or Schottky). However, _consistency_ across the ECAD is important to help the school children who will be assembling the PCBs.

In my experience many school children 'know' what an LED looks like, but aren't familiar with physical diodes (some might know its theory). Hence I recommend using 'LED' for LEDs and 'D' for diodes.

**Comment by micromouseonline** [comment]
Please re-check for consistency of naming. I believe this to be greatly improved.

**Comment by gbulmer** [comment]
Agreed. That is clearer. 
I might nit pick about 'Tn' (phototransistor) vs Q1 (bipolar transistor). However, I am okay with that.

So, I will close this.
