### ISSUE TITLE
Solder pads on PCB too small

### ISSUE THREAD

**Issue by davidhannaford** [ukmars/ukmarsbot#27]
The solder pads on the board are very small. With school soldering irons which don't have a fine tip it is going to be hard to get the heat onto the small pads to feed in the solder and get a good joint. For the components with leads it would be very easy to end up with just a blob of solder on the component lead about a millimetre away from the pad. I suspect that we will get quite a few scorched boards where the builders are having a job to get the heat down in the right place to get a good soldered joint.
> On all of the bots I have built I use oval pads, which means that you can still fit them onto a 0.1" pitch spacing but you have about 3 times as much pad to solder onto. This may not be possible on all of the board where space is particularly tight but the more places that we can have pads like the ones on the 4 way switch the easier it will be for people to successfully solder up the board

**Comment by micromouseonline** [comment]
Pads hav been resized and move in V1.3 (kicad)
