### ISSUE TITLE
Move diode D1 to allow more space for encoder PCBs

### ISSUE THREAD

**Issue by gbulmer** [ukmars/ukmarsbot#30]
Currently there is more than 10mm from the motors' axis to the motor connectors, and more than 14mm from the motors' axis to the MCU board. This space can be used for alternative encoder PCBs to be mounted on the rear of the motors.

However, diode D1 is in the plane of an encoder PCB mounted on the rear of the right motor. Hence the current position of diode D1 restricts the width of any encoder PCB on the right motor. 

Moving diode D1 out of that plane frees more width for motor-mounted encoder PCBs.

An encoder PCB could have a 'cut-out' to accommodate diode D1. 
However, PCB cut-outs increase constraints on the encoder PCB and increase complexity of encoder PCB panelisation. Both are undesirable.

_(Also, diode D1 may change in size (issue #26 ). So there may already be plans to pay some attention to it.)_

**Comment by micromouseonline** [comment]
D1 has been resized and move in V1.3 (kicad)
