### ISSUE TITLE
Add TB6612FNG module pin labels to UKMaRSBot PCB silkscreen

### ISSUE THREAD

**Issue by gbulmer** [ukmars/ukmarsbot#6]
Urgent, first Revision.

The TB6612FNG modules come without the pin headers, so there are four ways it could be 'plugged in' to the PCB.

Judging from the 'render' ukmarsbot-brd-20190731A.pdf it is a little unclear whether the TB6612FNG labels will be on the PCB silkscreen. There are two different colours of legend shown. That might be an artefact of the CAD software, or the ways 'layers' are set up, or an indication that they have a different status.

Putting the modules pin labels onto the UKMaRS PCB silkscreen should help reduce confusion, so that the one correct orientation is clear.

**Comment by micromouseonline** [comment]
That is a good idea.

**Comment by micromouseonline** [comment]
Dang! hit 'send'.
. . . and it is on my current revision - not yet uploaded.

**Comment by gbulmer** [comment]
That's good enough for me.
